version: 0.6.{build}
skip_tags: true
os: Visual Studio 2017
configuration: Release
platform: Any CPU
test: off
branches:
  only:
  - master
environment:
  NuGetApiKey:
    secure: FkbOZI29wVSKdzHuFOq9tY8cq05Sy6vFKwvqYnUhDVamagkTUrjNJElPPoACP8Ov
  CoverallsRepoToken:
    secure: l1sHD8smYdYmDTTRTPC0iMooNyPgm/sCOC3v3nBjJrKWLoOQoiAu2d0BGKY5BVOj
build_script:
- ps: .\build.ps1 --settings_skipverification=true
artifacts:
- path: artifacts\**\*.nupkg
- path: artifacts\**\site.zip
- path: artifacts\*.xml
- path: artifacts\*.html
notifications:
- provider: Email
  to:
  - robin@dapplo.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false