version: 0.1.{build}
skip_tags: true
configuration: Release
platform: Any CPU
shallow_clone: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  project: Dapplo.Windows.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
artifacts:
- path: '*.nupkg'
  name: NuGet package
notifications:
- provider: Email
  to:
  - robin@dapplo.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
deploy:
- provider: GitHub
  release: Dapplo.Windows-v$(appveyor_build_version)
  auth_token:
    secure: eBQPtXg53XgcvdcVY3wQAw6kkwNh+QhcsTDwzyQLLh6IOPyiePEaEhJR0D2YBjAj
  artifact: /.*\.nupkg/
  draft: false
- provider: NuGet
  skip_symbols: false
  api_key:
    secure: xkDQ385+smLqdzhESsXBJvnUjK4FZ4Djjrqi9tFR29dwESIvPYOrQAqgri5Nf/fA