version: 0.5.{build}
skip_tags: true
os: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_depth: 2
test: off
branches:
  only:
  - master
environment:
  NuGetApiKey:
    secure: FkbOZI29wVSKdzHuFOq9tY8cq05Sy6vFKwvqYnUhDVamagkTUrjNJElPPoACP8Ov
build_script:
- ps: .\build.ps1 --settings_skipverification=true
artifacts:
- path: artifacts\**\*.nupkg
- path: artifacts\**\site.zip
- path: artifacts\*.xml
- path: artifacts\*.html
notifications:
- provider: Email
  to:
  - robin@dapplo.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false