version: 0.8.{build}
skip_tags: true
os: Visual Studio 2017
configuration: Release
platform: Any CPU
test: off
branches:
  only:
  - master
  - develop
environment:
  NuGetApiKey:
    secure: Fu7vXeOuWmvDK7WGNsEbTIV2vhDV4P6PiK5k1+UZOmwldhCfvUvkA4HOkml+ZE/n
  CoverallsRepoToken:
    secure: l1sHD8smYdYmDTTRTPC0iMooNyPgm/sCOC3v3nBjJrKWLoOQoiAu2d0BGKY5BVOj
# Install dotnet core 3.0 latest (alpha!!), as this is not provided on AppVeyor yet
install:
- ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe'
- ps: Start-Process .\dotnet-sdk-latest-win-x64.exe "/install /norestart /quiet /log sdkinstall.log" -NoNewWindow -Wait
build_script:
- ps: .\build.ps1 --settings_skipverification=true
artifacts:
- path: sdkinstall.log
- path: src\**\*.nupkg
- path: artifacts\**\site.zip
- path: artifacts\*.xml
- path: artifacts\*.html
notifications:
- provider: Email
  to:
  - robin@dapplo.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false